name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "18.x"
  RUST_VERSION: "1.75.0"

jobs:
  # Frontend CI
  frontend:
    uses: ./.github/workflows/frontend-ci.yml
    secrets: inherit

  # Backend CI
  backend:
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit

  # Contracts CI
  contracts:
    uses: ./.github/workflows/contracts-ci.yml
    secrets: inherit

  # Services CI
  services:
    uses: ./.github/workflows/services-ci.yml
    secrets: inherit

  # Security Scanning
  security:
    uses: ./.github/workflows/security.yml
    secrets: inherit

  # Performance Testing
  performance:
    uses: ./.github/workflows/performance.yml
    secrets: inherit

  # Integration Tests
  integration:
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  # Summary
  summary:
    runs-on: ubuntu-latest
    needs: [frontend, backend, contracts, services, security, performance, integration]
    if: always()

    steps:
      - name: CI Summary
        run: |
          echo "🚀 CI Pipeline Summary:"
          echo "Frontend: ${{ needs.frontend.result }}"
          echo "Backend: ${{ needs.backend.result }}"
          echo "Contracts: ${{ needs.contracts.result }}"
          echo "Services: ${{ needs.services.result }}"
          echo "Security: ${{ needs.security.result }}"
          echo "Performance: ${{ needs.performance.result }}"
          echo "Integration: ${{ needs.integration.result }}"
          
          if [[ "${{ needs.frontend.result }}" == "failure" || 
                "${{ needs.backend.result }}" == "failure" || 
                "${{ needs.contracts.result }}" == "failure" || 
                "${{ needs.services.result }}" == "failure" || 
                "${{ needs.security.result }}" == "failure" || 
                "${{ needs.performance.result }}" == "failure" || 
                "${{ needs.integration.result }}" == "failure" ]]; then
            echo "❌ CI pipeline failed!"
            exit 1
          else
            echo "✅ All CI pipelines passed!"
          fi