name: Contracts CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "contracts-offerhub/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "contracts-offerhub/**"

env:
  RUST_VERSION: "1.75.0"
  SOROBAN_CLI_VERSION: "0.9.4"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            contracts-offerhub/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('contracts-offerhub/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Soroban CLI
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          cargo install --locked --version ${{ env.SOROBAN_CLI_VERSION }} soroban-cli

      - name: Set working directory
        run: echo "WORKING_DIR=contracts-offerhub" >> $GITHUB_ENV

      - name: Check formatting
        run: |
          cd ${{ env.WORKING_DIR }}
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cd ${{ env.WORKING_DIR }}
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build contracts
        run: |
          cd ${{ env.WORKING_DIR }}
          cargo build --release

      - name: Run tests
        run: |
          cd ${{ env.WORKING_DIR }}
          cargo test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts-build
          path: contracts-offerhub/target/release/
          retention-days: 7

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Install cargo-audit
        run: |
          source ~/.cargo/env
          cargo install cargo-audit

      - name: Run security audit
        run: |
          cd contracts-offerhub
          cargo audit

  integration-tests:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Install Soroban CLI
        run: |
          source ~/.cargo/env
          cargo install --locked --version ${{ env.SOROBAN_CLI_VERSION }} soroban-cli

      - name: Run integration tests
        run: |
          cd contracts-offerhub
          cargo test --test integration_test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: contracts-offerhub/test-results/
          retention-days: 7
