name: Services CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "services/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "services/**"

env:
  NODE_VERSION: "18.x"

jobs:
  freelance-matching:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./services/freelance-matching

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: services/freelance-matching/package-lock.json

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: services/freelance-matching/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-freelance-matching-${{ hashFiles('services/freelance-matching/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-freelance-matching-

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: freelance-matching-build-${{ matrix.node-version }}
          path: services/freelance-matching/dist/
          retention-days: 7

  security-audit:
    runs-on: ubuntu-latest
    needs: freelance-matching

    defaults:
      run:
        working-directory: ./services/freelance-matching

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: services/freelance-matching/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

  docker-build:
    runs-on: ubuntu-latest
    needs: [freelance-matching, security-audit]

    defaults:
      run:
        working-directory: ./services/freelance-matching

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/freelance-matching
          push: false
          tags: offer-hub/freelance-matching:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: services/freelance-matching/
          retention-days: 7
